# Run fMRIprep from the official docker repository
# This is the newest version as of 2024-10-24
# Nate Vack <njvack@wisc.edu>

container_image = docker://nipreps/mriqc:24.0.2
docker_override_entrypoint = true

transfer_output_files = ""

executable = run_mriqc.bash

request_disk = 96G
request_memory = 24G
request_cpus = 4

log = log/$(snum)-$(JobId).txt
error = err/$(snum)-$(JobId).txt
output = out/$(snum)-$(JobId).txt

arguments = $(snum)

queue snum from subjects-2024-10-25.txt
